### ISSUE TITLE
gitops bootstrap failure

### ISSUE THREAD

**Issue by tcskill** [cloud-native-toolkit/terraform-util-gitops-bootstrap#16]
failure when trying to run module unit tests that reference gitops-bootstrap.  Fails on the verify workflow:

Error: External Program Execution Failed
│ 
│   with module.gitops-bootstrap.data.external.argocd_config,
│   on .terraform/modules/gitops-bootstrap/main.tf line 53, in data "external" "argocd_config":
│   53:   program = ["bash", "${path.module}/scripts/get-argocd-config.sh"]
│ 
│ The data source received an unexpected error while attempting to execute
│ the program.
│ 
│ The program was executed, however it returned no additional error
│ messaging.
│ 
│ Program: /bin/bash
│ State: exit status 1
╵

**Comment by tcskill** [comment]
@seansund fyi

**Comment by mjperrins** [comment]
@triceam can you take a look at this its blocking `iascable` usage at the moment, we need to get past what had changed and improve the unit testing, @NoeSamaille is going to add more BOM generation unit testing in `iascable` repo so we can validate `main` branch boms in the process of releasing `iascable`

**Comment by seansund** [comment]
> @triceam can you take a look at this its blocking `iascable` usage at the moment, we need to get past what had changed and improve the unit testing, @NoeSamaille is going to add more BOM generation unit testing in `iascable` repo so we can validate `main` branch boms in the process of releasing `iascable`

@mjperrins You can't assign 3 people to the same issue. Only one assignee per issue or we will all be stomping on each other.

**Comment by seansund** [comment]
@tcskill I need more details on the test that failed. Was it the PR verify test for the SLS module or some other execution?

**Comment by mjperrins** [comment]
Not sure I assigned to 3 people just making them aware of the issue,
